[package]
name = "sequence"
version = "0.1.0"
authors = ["Craig Macomber <Craig.Macomber@microsoft.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
im-rc = "15.0.0"
num-integer = "0.1.44"
